Fix pip install, explicitly setting the package name
Pip refuses to install the package as the charm folder was added
to the top-level directory and setuptools auto-discovery is enabled.

  error: Multiple top-level packages discovered in a flat-layout:
  ['k8s_charm', 'mongo_webapp_sample'].

We'll solve the problem by customizing the setuptools auto-discovery.
At the same time, we're adding __init__.py files to avoid implicit
namespaces.